name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'practical3 '
      id: practical3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: 'practical3 '
        setup-command: 'java practical3.java '
        command: java pracitcal3
        input: Boy baked bread and baked biscuits
        expected-output: |-
          Enter a line of text:
          Words starting with 'b': [Boy, baked, bread, baked, biscuits]
          Words ending with 'ED': [baked, baked]
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRACTICAL3_RESULTS: "${{steps.practical3.outputs.result}}"
      with:
        runners: practical3
